### ISSUE TITLE
No way to delete image

### ISSUE THREAD

**Issue by timbowen** [ooksanen/acf-focuspoint#4]
With the latest version of ACF and WP there is no way to delete an acf-focuspoint image. If you delete it and then save the page, it comes back.

You can replace it with a new image, but you can't delete it.

**Comment by ooksanen** [comment]
Thanks for the heads up. Are you using the plugin with Gutenberg or TinyMCE / Classic Editor?

I can reproduce the bug at least on a site using Gutenberg so I suspect it might be because of changes in the way either ACF or Gutenberg saves the meta data. I'll definitely have a look into this at some stage.

**Comment by ooksanen** [comment]
This should be fixed now. Let me know if you still have problems deleting images.
